### ISSUE TITLE
Error building  wfmath  with clang

### ISSUE THREAD

**Issue by slacka** [worldforge/wfmath#9]
Building wfmath with clang results in:

`intersect.cpp:182:6: error: explicit specialization of 'Intersect<2>' after instantiation`

The full log can be found here:
http://clang.debian.net/logs/2016-08-30/wfmath_1.0.2+dfsg1-3_unstable_clang.log

**Comment by erikogenvik** [comment]
This has actually been fixed here, 2ec8d03c63290c3faefab1d55245cfb265fc76c7, but we haven't done a new release yet. Part of the reason is that we've bumped the dependency on Atlas to 0.7, which we also haven't done a release for yet.

**Comment by slacka** [comment]
Thanks! Closed with 2ec8d03

**Comment by erikogenvik** [comment]
Though the real bug here is that we haven't had a release in 2 years. However, for packages I'm thinking it shouldn't be too cumbersome to include that specific commit in the patches for the distro release.
We'll look into getting a new release out of the door though.
